### ISSUE TITLE
Offer Consulting Services

### ISSUE THREAD

**Issue by michael-spengler** [gitcoin-enterprise/gitcoin-enterprise#15]
1. For Enterprises
2. For potential Issue Solvers 

Perhaps in co-working mode with the gitcoin.co guys

Goal: 
**Fast and successful adoption within the corresponding enterprises**

**Comment by michael-spengler** [comment]
It would be cool if also the "Consulting Tasks" would be funded via GitCoin Enterprise.

**Comment by GitCoinEnterprise** [comment]
## This task has been funded via gitcoin-enterprise.org

This task has been funded with  
```
2 EIC by michael-spengler
```  

Solve this task to earn this bounty.  

With [https://gitcoin-enterprise.org](https://gitcoin-enterprise.org) you can: 

1. Solve the tasks you like 
2. Delegate the rest

**Comment by GitCoinEnterprise** [comment]
## Solution Approach entered via GitCoin Enterprise

@michael-spengler wants to solve this task by:  
```
I will do this quick and dirty :)

... by Friday
```

Please let him know if this is a good idea.  

The funders of this task can trigger the payout of their funding via [https://gitcoin-enterprise.org](https://gitcoin-enterprise.org)
