### ISSUE TITLE
Push Notifications for Developers when new Task was funded into Telegram Channel

### ISSUE THREAD

**Issue by michael-spengler** [gitcoin-enterprise/gitcoin-enterprise#24]
Goal: Find a quick match.

The support channel can easily be used for this. Log entries with loglevel <=1 shall be sent to the support channel.

**Comment by GitCoinEnterprise** [comment]
## This task has been funded

This task has been funded with  
```
18 EIC
```

These features are in experimental mode. You can use them via [https://gitcoin-enterprise.org](https://gitcoin-enterprise.org)

**Comment by GitCoinEnterprise** [comment]
## This task has been funded

This task has been funded with  
```
7 EIC
```

These features are in experimental mode. You can use them via [https://gitcoin-enterprise.org](https://gitcoin-enterprise.org)

**Comment by GitCoinEnterprise** [comment]
## This task has been funded

This task has been funded with  
```
4 EIC
```

These features are in experimental mode. You can use them via [https://gitcoin-enterprise.org](https://gitcoin-enterprise.org)

**Comment by GitCoinEnterprise** [comment]
## This task has been funded

This task has been funded with  
```
6 EIC
```

These features are in experimental mode. You can use them via [https://gitcoin-enterprise.org](https://gitcoin-enterprise.org)

**Comment by GitCoinEnterprise** [comment]
## This task has been funded

This task has been funded with  
```
16 EIC
```

These features are in experimental mode. You can use them via [https://gitcoin-enterprise.org](https://gitcoin-enterprise.org)

**Comment by GitCoinEnterprise** [comment]
## This task has been funded

This task has been funded with  
```
20 EIC
```

These features are in experimental mode. You can use them via [https://gitcoin-enterprise.org](https://gitcoin-enterprise.org)

**Comment by GitCoinEnterprise** [comment]
## This task has been funded

This task has been funded with  
```
109 EIC
```

These features are in experimental mode. You can use them via [https://gitcoin-enterprise.org](https://gitcoin-enterprise.org)
