### ISSUE TITLE
Scenario: Fund an Issue - Inform User when issue was not found - e.g. 404

### ISSUE THREAD

**Issue by michael-spengler** [gitcoin-enterprise/gitcoin-enterprise#27]

**Comment by GitCoinEnterprise** [comment]
## This task has been funded via gitcoin-enterprise.org

This task has been funded with  
```
20 EIC by michael-spengler
```  

Solve this task to earn this bounty.  

With [https://gitcoin-enterprise.org](https://gitcoin-enterprise.org) you can: 

1. Solve the tasks you like 
2. Delegate the rest
