### ISSUE TITLE
A difficult task which I would like to delegate :)

### ISSUE THREAD

**Issue by michael-spengler** [gitcoin-enterprise/gitcoin-enterprise#29]
just a demo task

**Comment by GitCoinEnterprise** [comment]
## This task has been funded via gitcoin-enterprise.org

This task has been funded with  
```
100 EIC by michael-spengler
```  

Solve this task to earn this bounty.  

With [https://gitcoin-enterprise.org](https://gitcoin-enterprise.org) you can: 

1. Solve the tasks you like 
2. Delegate the rest

**Comment by GitCoinEnterprise** [comment]
## Solution Approach entered via GitCoin Enterprise

@michael-spengler wants to solve this task by:  
```
I will delete the code :) 
Until Wednesday :) 
```

Please let him know if this is a good idea.  

The funders of this task can trigger the payout of their funding via [https://gitcoin-enterprise.org](https://gitcoin-enterprise.org)
