### ISSUE TITLE
A very difficult task for me

### ISSUE THREAD

**Issue by michael-spengler** [gitcoin-enterprise/gitcoin-enterprise#30]
just a demo task

**Comment by GitCoinEnterprise** [comment]
## This task has been funded via gitcoin-enterprise.org

This task has been funded with  
```
100 EIC by michael-spengler
```  

Solve this task to earn this bounty.  

With [https://gitcoin-enterprise.org](https://gitcoin-enterprise.org) you can: 

1. Solve the tasks you like 
2. Delegate the rest

**Comment by GitCoinEnterprise** [comment]
## This task has been funded via gitcoin-enterprise.org

This task has been funded with  
```
100 EIC by michael-spengler
```  

Solve this task to earn this bounty.  

With [https://gitcoin-enterprise.org](https://gitcoin-enterprise.org) you can: 

1. Solve the tasks you like 
2. Delegate the rest

**Comment by GitCoinEnterprise** [comment]
## Solution Approach entered via GitCoin Enterprise

@michael-spengler wants to solve this task by:  
```
I will solve this by Wednesday :) 
I'll add some details soon.
```

Please let him know if this is a good idea.  

The funders of this task can trigger the payout of their funding via [https://gitcoin-enterprise.org](https://gitcoin-enterprise.org)

**Comment by GitCoinEnterprise** [comment]
## This task has been funded via gitcoin-enterprise.org

This task has been funded with  
```
48 EIC by michael-spengler
```  

Solve this task to earn this bounty.  

With [https://gitcoin-enterprise.org](https://gitcoin-enterprise.org) you can: 

1. Solve the tasks you like 
2. Delegate the rest

**Comment by GitCoinEnterprise** [comment]
## This task has been funded via gitcoin-enterprise.org

This task has been funded with  
```
55 EIC by michael-spengler
```  

**The overall funding for this task is now: 103 EIC.**  

Solve this task to earn this bounty.  

With [https://gitcoin-enterprise.org](https://gitcoin-enterprise.org) you can: 

1. Solve the tasks you like 
2. Delegate the rest

**Comment by GitCoinEnterprise** [comment]
## This task has been funded via gitcoin-enterprise.org

This task has been funded with  
```
202 EIC by michael-spengler
```  

**The overall funding for this task is now: 305 EIC.**  

Solve this task to earn this bounty.  

With [https://gitcoin-enterprise.org](https://gitcoin-enterprise.org) you can: 

1. Solve the tasks you like 
2. Delegate the rest

**Comment by GitCoinEnterprise** [comment]
## Solution Approach entered via GitCoin Enterprise

@michael-spengler wants to solve this task by:  
```
i will do this quick and dirty until Wednesday.
```

Please let him know if this is a good idea.  

The funders of this task can trigger the payout of their funding via [https://gitcoin-enterprise.org](https://gitcoin-enterprise.org)
