### ISSUE TITLE
FYI I brought your project to the attention of the InnerSource community at the InnerSourceCommons slack group

### ISSUE THREAD

**Issue by dellagustin** [gitcoin-enterprise/gitcoin-enterprise#34]
You may want to join the discussion, and eventually use that space to host discussions on the tool.

Here is a link to the thread: https://innersourcecommons.slack.com/archives/C2EFRTS6A/p1584565362056500

You will find how to join the workspace here: http://innersourcecommons.org/contact/

Cheers and stay safe!

**Comment by michael-spengler** [comment]
Hi @dellagustin Thank you very much - I plan to take this forward in the context of arweave apps / https://nest.land/ ... 

feel free to join nest.land https://discord.gg/CJYvc2N
