### ISSUE TITLE
fix security issues based on security alerts for this repository

### ISSUE THREAD

**Issue by michael-spengler** [gitcoin-enterprise/gitcoin-enterprise#7]
During npm i some warnings come up.

**Comment by GitCoinEnterprise** [comment]
## This task has been funded via gitcoin-enterprise.org

This task has been funded with  
```
75 EIC by michael-spengler
```  

Solve this task to earn this bounty.  

With [https://gitcoin-enterprise.org](https://gitcoin-enterprise.org) you can: 

1. Solve the tasks you like 
2. Delegate the rest
